### ISSUE TITLE
Running tests work, debugging them fails

### ISSUE THREAD

**Issue by soc** [dinfuehr/dora#113] opened 2019-11-10 18:13 UTC
It's not limited to any specific test.

Here is the stacktrace and video from trying to debug one arbitrary test:

```
thread 'semck::clsdefck::tests::test_class_definition' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at /rustc/8431f261dd160021b6af85916f161a13dd101ca0/src/libstd/io/mod.rs:1412
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:141
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:207
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:473
  12: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
  13: rust_begin_unwind
             at src/libstd/panicking.rs:307
  14: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  15: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  16: core::result::Result<T,E>::unwrap
             at /rustc/8431f261dd160021b6af85916f161a13dd101ca0/src/libcore/result.rs:933
  17: dora::test::parse_with_errors
             at dora/src/test.rs:61
  18: dora::semck::tests::ok
             at dora/src/semck.rs:403
  19: dora::semck::clsdefck::tests::test_class_definition
             at dora/src/semck/clsdefck.rs:361
  20: dora::semck::clsdefck::tests::test_class_definition::{{closure}}
             at dora/src/semck/clsdefck.rs:360
  21: core::ops::function::FnOnce::call_once
             at /rustc/8431f261dd160021b6af85916f161a13dd101ca0/src/libcore/ops/function.rs:227
  22: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/8431f261dd160021b6af85916f161a13dd101ca0/src/liballoc/boxed.rs:922
  23: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  24: std::panicking::try
             at /rustc/8431f261dd160021b6af85916f161a13dd101ca0/src/libstd/panicking.rs:271
  25: std::panic::catch_unwind
             at /rustc/8431f261dd160021b6af85916f161a13dd101ca0/src/libstd/panic.rs:394
  26: test::run_test_in_process
             at src/libtest/lib.rs:1626
  27: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:1504
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

![debug-fail](https://user-images.githubusercontent.com/42493/68548506-08070900-03ee-11ea-9bdd-4d2ffcaeb13f.gif)

**Comment by dinfuehr** [comment] 2019-11-10 19:59
I think this is because tests recently moved. It seems that the working directory is different, Dora doesn't seem to find the stdlib files.

**Comment by dinfuehr** [comment] 2019-11-10 20:01
As a workaround for now, you can probably run the test from the `dora/dora` directory or adjust the path.

**Comment by dinfuehr** [comment] 2019-11-10 20:09
I've also added a commit to report a better error message for this. Not sure about how to fix this though.

**Comment by soc** [comment] 2019-11-10 20:33
Thanks! Adjusting the working dir works as a workaround, though it's a bit concerning that we seemingly lost seamless IDE support to debug things with this change. :-/

**Comment by dinfuehr** [comment] 2019-11-11 14:09
I agree. However I think the problem is how we load the stdlib files at the moment, not the commit that moved the stdlib. I guess we need to fix this by loading the bundled stdlib in the executable.

**Comment by dinfuehr** [comment] 2019-11-12 21:59
Should be fixed now, we now load the bundled stdlib in `cargo test`.

**Closed by dinfuehr** 2019-11-12 21:59 UTC

**Comment by soc** [comment] 2019-11-13 12:48
Cool, thanks! I will test later and report back!
